// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXqItNJH2c9MkdiL70cZ4KdUSp1vu4dgA',
    appId: '1:899363118853:web:950c6b4a1fcbf28b96e16c',
    messagingSenderId: '899363118853',
    projectId: 'smart-food-waste-managem-e4c29',
    authDomain: 'smart-food-waste-managem-e4c29.firebaseapp.com',
    storageBucket: 'smart-food-waste-managem-e4c29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD64BEnkVWyX9mUVGCXorvvamVKlIsITU',
    appId: '1:899363118853:android:86fa4ac49d849dbe96e16c',
    messagingSenderId: '899363118853',
    projectId: 'smart-food-waste-managem-e4c29',
    storageBucket: 'smart-food-waste-managem-e4c29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTTau6mexjdGoSO-6Hv8K2-jhSQUX7b90',
    appId: '1:899363118853:ios:72ea4d14a86cbe7796e16c',
    messagingSenderId: '899363118853',
    projectId: 'smart-food-waste-managem-e4c29',
    storageBucket: 'smart-food-waste-managem-e4c29.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTTau6mexjdGoSO-6Hv8K2-jhSQUX7b90',
    appId: '1:899363118853:ios:72ea4d14a86cbe7796e16c',
    messagingSenderId: '899363118853',
    projectId: 'smart-food-waste-managem-e4c29',
    storageBucket: 'smart-food-waste-managem-e4c29.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXqItNJH2c9MkdiL70cZ4KdUSp1vu4dgA',
    appId: '1:899363118853:web:e33edf190d929ded96e16c',
    messagingSenderId: '899363118853',
    projectId: 'smart-food-waste-managem-e4c29',
    authDomain: 'smart-food-waste-managem-e4c29.firebaseapp.com',
    storageBucket: 'smart-food-waste-managem-e4c29.firebasestorage.app',
  );
}
